//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Desdinova Modeler.rc
//
#define MENU_FILE_NEW                   0
#define VER_INFO                        1
#define DIALOG_FOG                      9
#define DIALOG_ABOUT                    105
#define IDB_DESDINOVA                   107
#define DIALOG_SPLASH                   118
#define MENU_HELP_ABOUT                 123
#define MENU_VIEW_WIREFRAME             129
#define DIALOG_MAIN                     130
#define MENU_FILE_SAVE                  133
#define MENU_FILE_EXIT                  135
#define ICON1                           147
#define DIALOG_RENDERZONE1              147
#define IDB_SPLASH                      155
#define MENU_UTILITIES_CAPTURE          157
#define MENU_VIEW_LOD                   162
#define MENU_VIEW_FRUSTRUMCULLING       163
#define MENU_VIEW_LIGHTING              164
#define MENU_VIEW_INFO                  165
#define MENU_VIEW_AXES                  169
#define DIALOG_LIGHTSMANAGER            171
#define DIALOG_CAMERACONTROL            172
#define IDB_TOOLBAR2                    177
#define MENU_EDIT_MODELSMANAGER         178
#define MENU_EDIT_LIGHTSMANAGER         179
#define MENU_EDIT_CAMERACONTROL         180
#define DIALOG_MODELSMANAGER            186
#define MENU_FILE_CLOSE                 192
#define MENU_BOUNDING_BOX               210
#define MENU_BOUNDING_SPHERE            211
#define MENU_BOUNDING_NONE              212
#define DIALOG_ENTITIESMANAGER          220
#define DIALOG_PARTICLESMANAGER         222
#define MENU_EDIT_PARTICLESMANAGER      223
#define DIALOG_OPEN                     226
#define DIALOG_NEW                      227
#define MENU_FILE_OPEN                  228
#define IDB_PARENT                      229
#define IDB_CHILD                       231
#define MENU_HELP_HELP                  232
#define MENU_HELP_SITE                  234
#define DIALOG_SAVE                     238
#define MENU_VIEW_GRID                  239
#define IDD_DIALOG1                     242
#define DIALOG_RENDERZONE2              242
#define MENU_MAIN                       1001
#define OK_BUT                          1022
#define RENDER_ZONE                     1060
#define LAB_CAM_POSX                    1185
#define LAB_CAM_POSY                    1186
#define LAB_CAM_POSZ                    1187
#define LAB_FACES                       1188
#define LAB_CAM_VIEWX                   1188
#define LAB_VERTICES                    1189
#define TXT_CAM_SPEED                   1191
#define LAB_CAM_VIEWY                   1192
#define LAB_CAM_VIEWZ                   1193
#define LAB_HEIGHT                      1199
#define LAB_WIDTH                       1200
#define LAB_DEPTH                       1202
#define CHK_LIGHT_RANGE                 1202
#define CHK_LIGHT_POS                   1203
#define TXT_PAR_VELX                    1208
#define TXT_PAR_VELY                    1209
#define TXT_PAR_VELZ                    1210
#define TXT_PAR_GRAVX                   1211
#define TXT_PAR_GRAVY                   1212
#define LAB_RADIUS                      1213
#define TXT_PAR_GRAVZ                   1213
#define TXT_PAR_R                       1214
#define TXT_PAR_G                       1215
#define TXT_PAR_B                       1216
#define TXT_PAR_A                       1217
#define BUT_PARTICLES_SET               1218
#define TXT_PAR_WINDX                   1219
#define TXT_PAR_WINDY                   1220
#define TXT_PAR_WINDZ                   1221
#define BUT_CAM_SETSPEED                1237
#define TXT_LIGHT_AMBIENT_R             1237
#define TXT_LIGHT_AMBIENT_G             1238
#define IDC_COMBO1                      1239
#define TXT_LIGHT_AMBIENT_B             1240
#define IDC_BUTTON2                     1241
#define IDC_BUTTON3                     1242
#define BUT_LIGHT_SET                   1243
#define IDC_COMBO3                      1245
#define TXT_LIGHT_AMBIENT_A             1246
#define TXT_LIGHT_SPECULAR_R            1247
#define TXT_LIGHT_SPECULAR_G            1248
#define TXT_LIGHT_SPECULAR_B            1249
#define TXT_LIGHT_POS_X                 1251
#define TXT_LIGHT_POS_Y                 1252
#define TXT_LIGHT_POS_Z                 1253
#define TXT_LIGHT_DIR_X                 1255
#define TXT_LIGHT_DIR_Y                 1256
#define TXT_LIGHT_DIR_Z                 1257
#define TXT_LIGHT_ATT_0                 1258
#define TXT_LIGHT_ATT_1                 1259
#define TXT_LIGHT_ATT_2                 1260
#define TXT_LIGHT_RANGE                 1261
#define TXT_LIGHT_FALLOFF               1264
#define TXT_LIGHT_PHI                   1265
#define TXT_LIGHT_THETA                 1266
#define IDC_EDIT1                       1269
#define IDC_EDIT2                       1270
#define IDC_EDIT3                       1271
#define TXT_PAR_LIFE                    1272
#define TXT_PAR_SIZE                    1273
#define TXT_LIGHT_DIFFUSE_R             1274
#define TXT_PAR_VELOCITY                1274
#define TXT_LIGHT_DIFFUSE_G             1275
#define TXT_LIGHT_DIFFUSE_B             1276
#define TXT_LIGHT_DIFFUSE_A             1277
#define TXT_LIGHT_SPECULAR_A            1278
#define IDC_BUTTON1                     1280
#define LAB_ABOUT_TITLE                 1281
#define BUT_OPEN_PAR                    1281
#define BUT_SAVE_CANCEL                 1281
#define IDC_RADIO1                      1282
#define BUT_OPEN_ENTITY                 1282
#define IDC_RADIO2                      1283
#define BUT_OPEN_CANCEL                 1283
#define IDC_RADIO3                      1284
#define IDC_RADIO4                      1285
#define IDC_RADIO5                      1286
#define IDC_EDIT4                       1287
#define IDC_EDIT5                       1288
#define IDC_EDIT6                       1289
#define IDC_CHECK1                      1290
#define CB_LODID                        1297
#define TXT_LODDISTANCE                 1299
#define IDC_IMAGE                       1321
#define MENU_EDIT_ENTITIESMANAGER       1325
#define TXT_ANCHORPOSX                  1326
#define TXT_ANCHORPOSY                  1327
#define TXT_ANCHORPOSZ                  1328
#define TXT_ANCHORROTX                  1329
#define TXT_ANCHORROTY                  1330
#define TXT_ANCHORROTZ                  1331
#define TXT_CHILD_FILENAME              1332
#define BUT_CHILD_SET                   1333
#define CHK_CHILD_ENABLE                1334
#define TXT_ANCHORSCALEX                1335
#define BUT_CHILD_ADD                   1336
#define CHK_ANCHOR_ENABLE               1337
#define TXT_ANCHORSCALEY                1338
#define CHK_CHILD_ACTIVE                1339
#define BUT_CHILD_REMOVE                1340
#define TXT_ANCHORSCALEZ                1341
#define TXT_CHILDPOSX                   1342
#define TXT_CHILDPOSY                   1343
#define TXT_CHILDPOSZ                   1344
#define TXT_CHILDROTX                   1345
#define TXT_CHILDROTY                   1346
#define TXT_PAR_MAX                     1347
#define TXT_CHILDROTZ                   1347
#define TXT_PAR_RELEASE                 1348
#define TXT_CHILDSCALEX                 1348
#define TXT_PAR_INTERVAL                1349
#define TXT_CHILDSCALEY                 1349
#define CHK_PAR_RESISTENCE              1350
#define TXT_CHILDSCALEZ                 1350
#define TXT_PAR_POSX                    1352
#define TXT_PAR_POSY                    1353
#define TXT_PAR_POSZ                    1354
#define TXT_PAR_DISTANCEX               1356
#define BUT_OPEN_MODEL                  1357
#define TXT_PAR_DISTANCEY               1357
#define TXT_PAR_DISTANCEZ               1358
#define BUT_NEW_ENTITY                  1359
#define BUT_NEW_PAR                     1360
#define BUT_NEW_CANCEL                  1361
#define TREE_MANAGER                    1368
#define TXT_CHILD_TOTAL                 1369
#define LAB_POS                         1370
#define LAB_ROT                         1374
#define LAB_POS2                        1375
#define LAB_ROT2                        1376
#define LAB_POS3                        1377
#define LAB_POS4                        1378
#define LAB_SCALE                       1381
#define LAB_SCALE2                      1382
#define BUT_SAVE_SAVE                   1383
#define TXT_SAVE_NAME                   1384
#define BUT_PARTICLES_LOAD              1385
#define LAB_PAR_TEXTURE                 1386
#define BUT_PARTICLES_COLOR             1388
#define BUT_RELOAD                      1393
#define CB_PAR_TYPE                     1394
#define CHK_PAR_RELATIVEY               1395
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1403
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
